### PR TITLE
Validity check for email

### PR DESCRIPTION
**Pull request by MaZZly**
Regex check for input field of `type="email"`

Otherwise the spinner will start spinning, while browser will prevent submit() due to required attr and invalid email

### CODE REVIEW

**Comment by r3wt** [comment]
How can i open an issue? I can't seem to get ladda to work in Zurb Foundation

**Comment by billpratt** [comment]
:+1: for pull request

Confirmed bug can been seen here: http://jsfiddle.net/4hu5ksze/

**Comment by hakimel** [comment]
Thanks @MaZZly, this has been merged. Anyone know what the browser support for `checkValidity` is like? Would be nice to switch to just trusting the browser's own validation in the future.

@r3wt Issues are disabled since I don't have time to maintain/debug them. Happy to accept pull requests though.

**Comment by MaZZly** [comment]
According to http://caniuse.com/#feat=form-validation the only ones lagging behind are Apple

**Comment by hakimel** [comment]
Got it. If we need to stick to custom validation for one browser, I guess we might as well for all of them.

**Comment by MaZZly** [comment]
@hakimel  I've since making that pull request realized that the regexp does not follow the standard for email addresses.. For example name@server is totally valid according to specs... The regexp I put is requiring name@server.tld

Not sure if this is going to be a problem since I've myself never seen an email without the .tld part but =D

**Comment by billpratt** [comment]
:+1: for using the browser's validity. If you turned on issues, you could mark this as a feature and have someone pick it up and submit a pull request. That way there is a public record of features that need implemented.

**Comment by billpratt** [comment]
@MaZZly My vote is if browser validity accepts "name@server" then this should support it also. If ladda is changed to use the browser's validation, its doesnt matter.

**Comment by billpratt** [comment]
@hakimel Are you pushing this change to bower?

**Comment by hakimel** [comment]
Yeah, will do that soon

**Comment by inghamc** [comment]
@hakimel, I submitted #58 to feature detect and prefer checkValidity() on the enclosing form.  Fallback behavior for IE9.

**Pull request merged**
